### ISSUE TITLE
MECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

### ISSUE THREAD

**Issue by Asgarrrr** [Woulfty/TP3-SN-CF#1]
CARTE C'EST PAS AVEC UN PUTAIN DE "K"

![Capture](https://user-images.githubusercontent.com/36574651/141771299-36f1bf58-f30f-460e-9601-ce0382e0f903.PNG)

**Comment by Woulfty** [comment]
C'était fait exprès ^^' 
Désolé

**Comment by Asgarrrr** [comment]
Je plaisante
